.github/workflows/auto-pull-request.yml
=> ci: auto pr creation

.github/workflows/auto-pull-request.yml
=> ci: do not trigger pr on new tag

.github/workflows/auto-pull-request.yml, .github/workflows/run-tests.yml, e2e/auth.setup.ts, e2e/global.teardown.ts, e2e/login.spec.ts, e2e/logs.spec.ts, e2e/projects.spec.ts, e2e/templates.spec.ts, e2e/utils/db.ts, packages/backend/src/api/v1/index.ts, packages/backend/src/utils/misc.ts, packages/frontend/components/blocks/CopyText.tsx, packages/frontend/components/blocks/RunInputOutput.tsx, packages/frontend/components/layout/index.tsx, packages/frontend/pages/logs/index.tsx, playwright.config.ts
=> fix: access public run

packages/frontend/pages/logs/index.tsx
=> chore: remove trailing questionmark in url

packages/shared/checks/serialize.ts
=> fix: decimal number deserialization in checks

e2e/users.spec.ts, e2e/utils/db.ts, packages/backend/src/api/v1/external-users.ts
=> fix: external user list

packages/backend/src/utils/openai.ts, packages/backend/src/utils/playground.ts
=> feat: add azure openai support

.github/workflows/build-push-deploy.yml
=> build: add arm64 to docker images builds

packages/frontend/components/blocks/RunInputOutput.tsx
=> fix: stray a

packages/frontend/components/checks/Picker.tsx, packages/frontend/components/checks/SmartSelectInput.tsx, packages/shared/checks/index.ts
=> style: improve check filters display

packages/frontend/components/checks/Picker.tsx
=> fix: and or dropdown render

packages/backend/src/api/v1/runs/index.ts, packages/frontend/components/blocks/Feedbacks/index.tsx, packages/frontend/components/blocks/OldFeedback.tsx, packages/frontend/components/blocks/RunChat.tsx, packages/frontend/components/blocks/RunInputOutput.tsx, packages/frontend/components/checks/ChecksUIData.tsx, packages/frontend/components/checks/SmartSelectInput.tsx, packages/frontend/pages/logs/[id].tsx, packages/frontend/pages/logs/index.tsx, packages/frontend/utils/dataHooks.ts, packages/frontend/utils/datatable.tsx, packages/shared/checks/index.ts, packages/shared/types/index.ts, packages/shared/types/log.ts
=> feat: add feedback from ui

.github/workflows/build-push-deploy.yml
=> fix: pipeline

packages/backend/src/api/v1/auth/index.ts, packages/frontend/components/blocks/Feedbacks/index.tsx, packages/frontend/components/layout/Sidebar.tsx, packages/frontend/pages/signup.tsx
Fix invalid hardcoded data in cal.com setup
Add where did you find us field
Fix signup order
Fix crash locally because org.license is undefined
=> where did you find us + fixes

packages/backend/src/api/v1/users.ts, packages/frontend/pages/join.tsx, packages/frontend/pages/team.tsx, packages/shared/checks/serialize.ts
=> fix: team full

packages/frontend/pages/team.tsx
=> fix: project select for unallowed org

packages/backend/src/api/v1/users.ts, packages/frontend/pages/team.tsx
=> fix: user allowance

.github/workflows/build-push-deploy.yml
=> ci: improv deployment speed

packages/backend/src/index.ts
=> feat: increase request body size limit

packages/frontend/pages/settings.tsx, packages/frontend/pages/signup.tsx, packages/frontend/pages/team.tsx
=> fix: typos

packages/backend/src/api/v1/filters.ts
=> refactor: remove filter feedback

README.md
Original URL led to 500 page, fixed it.
=> Fixed full documentation URL
